apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 8085
      targetPort: 8085
    - name: prometheus
      protocol: TCP
      port: 9100
      targetPort: 9100