apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core
  ports:
    - name: core 
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: prometheus 
      protocol: TCP
      port: 9100
      targetPort: 9100