apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 8081
      targetPort: 8081
      
    - name: prometheus
      protocol: TCP
      port: 9100
      targetPort: 9100
  loadBalancerIP: "35.246.109.70"
