apiVersion: v1
kind: Service
metadata:
  name: lock-service
spec:
  selector:
    app: lock
  ports:
    - name: lock
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: prometheus
      protocol: TCP
      port: 9100
      targetPort: 9100